name: Gitflow Action for R Package Development
run-name: ${{ github.actor }} now ${{ github.event_name }} to ${{ github.ref_name }}

on:
  push:
    branches: ['*', '!dev', '!main']
    
  pull_request:
    types: ['opened', 'closed']
    branches: ['main', 'release*']

jobs:
  User_Inputs:
    runs-on: ubuntu-latest
    env:
      set_image_to_be_used: "<>"
      action_version: main
    
    outputs:
      image_to_be_used: ${{ steps.pass_input.outputs.image_to_be_used }}
      action_version: ${{ steps.pass_input.outputs.action_version }}
      
    steps:
      - name: Print action scripts to be used
        id: pass_input
        shell: bash
        run: |
          echo "image_to_be_used=${{ env.set_image_to_be_used }}" >> $GITHUB_OUTPUT
          echo "Image: ${{ env.set_image_to_be_used }}"
          
          echo "action_version=${{ env.action_version }}" >> $GITHUB_OUTPUT
          echo "Action version to use: ${{ env.action_version }}"
        
  Activating_Parser:
    needs: [User_Inputs]
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/parser.yml@master
    with:
      image_to_use: "${{ needs.User_Inputs.outputs.image_to_be_used }}"
      verions_to_use: "${{ needs.User_Inputs.outputs.action_version }}"
      
