name: Gitflow-R Action Pack Version- Main
run-name: Activated by ${{ github.actor }}

on:
  workflow_call:
    inputs:
    
      image_to_use:
        required: true
        type: string
        
      test:
        required: false
        default: 'No'
        type: string

jobs: 
  Checks:
    runs-on: ubuntu-latest
    outputs:
      release_match: ${{ steps.checks.outputs.release_match }}
      pull_check: ${{ steps.checks.outputs.pull_check }}
      main_match: ${{ steps.checks.outputs.main_match }}
      merged_check: ${{ steps.checks.outputs.merged_check }}
    steps:
      - name: Show Job Info
        id: checks
        run: |
          echo "Image to use: ${{ inputs.image_to_use }}"
          echo "Event Branch:  ${{ github.ref_name }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Pull Merged: ${{ github.event.pull_request.merged }}"
          echo "Pull Request Branch:  ${{ github.base_ref }}"
          
          
          export pull_branch="${{ github.base_ref }}"
          export pull_merged="${{ github.event.pull_request.merged }}"
          export event_name="${{ github.event_name }}"
          export event_branch="${{ github.ref_name }}"
          
          if [[ ${{ github.event_name }} == pull_request ]]; then
              echo "pull_check=Yes" >> "$GITHUB_OUTPUT"
              echo "pull_check=Yes"
            else
              echo "pull_check=No" >> "$GITHUB_OUTPUT"
          fi
          
          if [[ -z "$pull_branch" ]]; then
            echo "release_match=No" >> "$GITHUB_OUTPUT"
            echo "main_match=No" >> "$GITHUB_OUTPUT"
          else
            if [[ $pull_branch == release* ]]; then
                echo "release_match=Yes" >> "$GITHUB_OUTPUT"
                echo "release_match=Yes"
            fi
            
            if [[ $pull_branch == main ]]; then
              echo "main_match=Yes" >> "$GITHUB_OUTPUT"
              echo "main_match=Yes"
            fi
          fi
          
          if [[ -z "$pull_merged" ]]; then
            echo "merged_check=No" >> "$GITHUB_OUTPUT"
          else
            if [[ $pull_merged == true ]]; then
                echo "merged_check=Yes" >> "$GITHUB_OUTPUT"
                echo "merged_check=Yes"
            fi
          fi
          
  Gitflow_R_Test:
    needs: [Checks]
    if: ${{ inputs.test == 'Yes' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/test_actions.yml@DSPWorkflow

  Check_Pushed_Scripts_version_main:
    needs: [Checks]
    if: ${{ github.event_name == 'push' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Commit.yml@DSPWorkflow
    with:
      image_to_use: "${{ inputs.image_to_use }}"
  
  Check_Merge_to_Release_version_main:
    needs: [Checks]
    if: ${{ needs.Checks.outputs.pull_check == 'Yes' && needs.Checks.outputs.merged_check != 'Yes' && needs.Checks.outputs.release_match == 'Yes' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Merge_to_Release.yml@DSPWorkflow
    with:
      image_to_use: "${{ inputs.image_to_use }}"
      
  Check_Merge_to_Main_version_main:
    needs: [Checks]
    if: ${{ needs.Checks.outputs.pull_check == 'Yes' && needs.Checks.outputs.merged_check != 'Yes' && needs.Checks.outputs.main_match == 'Yes' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Merge_to_Main.yml@DSPWorkflow
    with:
      image_to_use: "${{ inputs.image_to_use }}"
      
  Post_Processing_for_Merge_to_Main_version_main:
    needs: [Checks]
    if: ${{ needs.Checks.outputs.pull_check == 'Yes' && needs.Checks.outputs.merged_check == 'Yes' && needs.Checks.outputs.main_match == 'Yes' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Append_File_On_Merged_to_Main.yml@DSPWorkflow
    with:
      image_to_use: "${{ inputs.image_to_use }}"
