name: Gitflow-R Action Pack Version- Main
run-name: Activated by ${{ github.actor }}

on:
  workflow_call:
    inputs:
    
      image_to_use:
        required: true
        type: string
        
      test:
        required: false
        default: 'No'
        type: string

jobs: 
  Checks:
    runs-on: ubuntu-latest
    outputs:
      release_match: ${{ steps.checks.outputs.release_match }}
      pull_check: ${{ steps.checks.outputs.pull_check }}
      main_match: ${{ steps.checks.outputs.main_match }}
      merged_check: ${{ steps.checks.outputs.merged_check }}
    steps:
      - name: Show Job Info
        id: checks
        run: |
          echo "Image to use: ${{ inputs.image_to_use }}"
          echo "Event Branch:  ${{ github.ref_name }}"
          export curernt_branch="${{ github.base_ref }}"
          
          echo "Pull Request Branch:  ${{ github.base_ref }}"
          if [[ ${{ github.base_ref }} == release* ]]; then
              echo "release_match=yes" >> "$GITHUB_OUTPUT"
              echo "release_match=yes"
          fi
          
          if [[ ${{ github.base_ref }} == main ]]; then
              echo "main_match=yes" >> "$GITHUB_OUTPUT"
              echo "main_match=yes"
          fi
          
          echo "Event Name: ${{ github.event_name }}"
          if [[ ${{ github.event_name }} == pull_request ]]; then
              echo "pull_check=yes" >> "$GITHUB_OUTPUT"
              echo "pull_check=yes"
          fi
          
          echo "Pull Merged: ${{ github.event.pull_request.merged }}"
          if [[ ${{ github.event.pull_request.merged }} == true ]]; then
              echo "merged_check=yes" >> "$GITHUB_OUTPUT"
              echo "merged_check=yes"
          fi
    
  Gitflow_R_Test:
    needs: [Checks]
    if: ${{ inputs.test == 'Yes' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/test_actions.yml@master

  Check_Pushed_Scripts_verion_main:
    needs: [Checks]
    if: ${{ github.event_name == 'push' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Commit.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"
  
  Check_Merge_to_Release_verion_main:
    needs: [Checks]
    if: ${{ needs.Checks.outputs.pull_check == 'Yes' && needs.Checks.outputs.merged_check != 'Yes' && needs.Checks.outputs.release_match == 'Yes' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Merge_to_Release.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"
      
  Check_Merge_to_Main_verion_main:
    needs: [Checks]
    if: ${{ needs.Checks.outputs.pull_check == 'Yes' && needs.Checks.outputs.merged_check != 'Yes' && needs.Checks.outputs.main_match == 'Yes' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Merge_to_Main.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"
      
  Post_Processing_for_Merge_to_Main_version_main:
    needs: [Checks]
    if: ${{ needs.Checks.outputs.pull_check == 'Yes' && needs.Checks.outputs.merged_check == 'Yes' && needs.Checks.outputs.main_match == 'Yes' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Append_File_On_Merged_to_Main.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"