name: Gitflow-R Action Pack Version- Main
run-name: Activated by ${{ github.actor }}

on:
  workflow_call:
    inputs:
    
      image_to_use:
        required: true
        type: string
      
      event_name:
        required: true
        type: string
        
      pull_merged:
        required: true
        type: string  
        
      event_branch:
        required: true
        type: string
      
      test:
        required: false
        default: No
        type: string

jobs: 
  Show_Job_Trigger:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Image to use: ${{ inputs.image_to_use }}"
          echo "Event Branch:  ${{ inputs.event_branch }}"
          echo "Event Name: ${{ inputs.event_name }}"
          echo "Pull Merged: ${{ inputs.pull_merged }}"
    
  Gitflow_R_Test:
    if: ${{ inputs.test == 'Yes' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/test_actions.yml@master
    with:
      event_name: "${{ github.event_name }}"
      pull_merged: "${{ github.event.pull_request.merged }}"

  Check_Pushed_Scripts_verion_main:
    if: ${{ inputs.event_name == 'push' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Commit.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"
  
  Check_Merge_to_Release_verion_main:
    if: ${{ inputs.event_name == 'pull_request' && inputs.pull_merged == 'false' && inputs.event_branch == 'release*' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Merge_to_Release.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"
      
  Check_Merge_to_Main_verion_main:
    if: ${{ inputs.event_name == 'pull_request' && inputs.pull_merged == 'false' && inputs.event_branch == 'main' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Merge_to_Main.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"
      
  Post_Processing_for_Merge_to_Main_version_main:
    if: ${{ inputs.event_name == 'pull_request' && inputs.pull_merged == 'true' && inputs.event_branch == 'main' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Append_File_On_Merged_to_Main.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"