name: Gitflow-R Action Pack Version- Main
run-name: Activated by ${{ github.actor }}

on:
  workflow_call:
    inputs:
    
      image_to_use:
        required: true
        type: string
      
      event_name:
        required: true
        type: string
        
      pull_merged:
        required: true
        type: string  
        
      event_branch:
        required: true
        type: string

jobs: 
  Check_Pushed_Scripts_verion_main:
    if: ${{ inputs.event_name == 'push' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Commit.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"
  
  Check_Merge_to_Release_verion_main:
    if: ${{ inputs.event_name == 'pull_request' && inputs.pull_merged == 'false' && inputs.event_branch == 'release*' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Merge_to_Release.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"
      
  Check_Merge_to_Main_verion_main:
    if: ${{ inputs.event_name == 'pull_request' && inputs.pull_merged == 'false' && inputs.event_branch == 'main' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Merge_to_Main.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"
      
  Post_Processing_for_Merge_to_Main_version_main:
    if: ${{ inputs.event_name == 'pull_request' && inputs.pull_merged == 'true' && inputs.event_branch == 'main' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Append_File_On_Merged_to_Main.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"