name: Gitflow-R Action Pack Version- Main
run-name: Activated by ${{ github.actor }}

on:
  workflow_call:
    inputs:
    
      image_to_use:
        required: true
        type: string
        
      test:
        required: false
        default: No
        type: string

jobs: 
  Show_Job_Trigger:
    id: check-branch
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Image to use: ${{ inputs.image_to_use }}"
          echo "Event Branch:  ${{ github.ref_name }}"
          echo "Pull Request Branch:  ${{ github.base_ref }}"
          if [[ ${{ github.event.ref }} == "release*" ]]; then
              echo "release_match=true" >> $GITHUB_OUTPUT
          fi
          echo "Event Name: ${{ github.event_name }}"
          echo "Pull Merged: ${{ github.event.pull_request.merged }}"
    
  Gitflow_R_Test:
    if: ${{ inputs.test == 'Yes' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/test_actions.yml@master
    with:
      event_name: "${{ github.event_name }}"
      pull_merged: "${{ github.event.pull_request.merged }}"

  Check_Pushed_Scripts_verion_main:
    if: ${{ github.event_name == 'push' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Commit.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"
  
  Check_Merge_to_Release_verion_main:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == 'false' && steps.check-branch.outputs.release_match == 'true' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Merge_to_Release.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"
      
  Check_Merge_to_Main_verion_main:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == 'false' && github.base_ref == 'main' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Merge_to_Main.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"
      
  Post_Processing_for_Merge_to_Main_version_main:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == 'true' && github.base_ref == 'main' && inputs.test == 'No' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Append_File_On_Merged_to_Main.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"