name: Adding documentation and update GitHub Page
run-name: Action on Merged main by ${{ github.actor }} 

on:
  workflow_call:
    inputs:
    
      image_to_use:
        required: true
        type: string
      
jobs:
  Adding_documentation_files_and_publish_page:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image_to_use }}
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
         
    steps:
      - run: echo "Checking in ${{ inputs.image_to_use }}"
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          
      - name: Generating files with Document
        id: prepare-push 
        if: ${{ success() }}
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          cd $current_wd
          
          export MY_GIT_TOKEN=${{ secrets.GITHUB_TOKEN }}
          export MY_GIT_USERNAME=${{ github.actor }}
          export MY_GIT_EMAIL=${{ github.event.pusher.email }}
          
          git config --global user.name "$MY_GIT_USERNAME"
          git config --global user.email "$MY_GIT_EMAIL"
          git config --global url."https://api:$MY_GIT_TOKEN@github.com/".insteadOf "https://github.com/"
          git config --global url."https://ssh:$MY_GIT_TOKEN@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://git:$MY_GIT_TOKEN@github.com/".insteadOf "git@github.com:"
          
          git config --global --add safe.directory "$current_wd"
          
          git clone https://github.com/${GITHUB_REPOSITORY}.git
          
          cd ${GITHUB_REPOSITORY#*/}
          
          apt update && apt-get install -y --no-install-recommends pandoc
          
          git checkout main
          
          R -e '.libPaths(c("/renv/library/R-4.1/x86_64-pc-linux-gnu",.libPaths()));library(devtools);document();library(pkgdown);build_site_github_pages()'
          
          cat $(pwd)/NAMESPACE

          git add ./NAMESPACE ./man/*
          
          echo $(git commit -a -m "Adding auto-generated files") > commit_log.log
          
          cat commit_log.log
          
          echo "Performing check now"
          export nothing_for_commit="$(grep -Po "nothing to commit" commit_log.log)"
          
          if [ -n "${nothing_for_commit}" ]; then
            echo "Commit check failed with message: $nothing_for_commit" 
          else
            echo "Pushing changes now."
            git push -f origin main
          fi

          git add ./docs/*
          git commit -a -m "Adding docs for gitpage"
          
          echo "Now pushing GitHub Page Documents"
          
          echo $(git checkout github_page) > checkout_check.log
          
          export no_branch="$(grep -Po "did not match any file(s) known" checkout_check.log)"
          
          if [ -n "${no_branch}" ]; then
            git checkout -b github_page
          fi
          
          git checkout -f main ./docs
          
          echo $(git commit -a -m "Updating GitHub Page") > commit_log.log
          
          cat commit_log.log
          
          export nothing_for_commit="$(grep -Po "nothing to commit" commit_log.log)"
          
          if [ -n "${nothing_for_commit}" ]; then
            echo "Commit check failed with message: $nothing_for_commit" 
          else
            echo "Pushing changes now."
            git push -f origin github_page
          fi
          
          echo "Process completed."
    