name: Merging to Release
run-name: ${{ github.actor }} is merging "${{ github.ref_name }}" to release

on:
  workflow_call:
    inputs:
      
      image_to_use:
        required: true
        type: string
      
      action_branch:
        required: false
        type: string
      
jobs:
  All_Unit_Tests:
    name: Pull Request from ${{ github.ref_name }} to Release by ${{ github.actor }}
    runs-on: ubuntu-latest
    container: 
      image: ${{ inputs.image_to_use }}
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
         
    steps:
      - run: echo "Checking in ${{ inputs.image_to_use }}"
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      
      - id: Build_check
        name: R Build and Checks
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          
          git clone https://github.com/fnlcr-bids-sdsi/gitflow-R.git
          
          cd gitflow-R
          
          git checkout "${{ inputs.action_branch }}"
          
          cd -
          
          bash $current_wd/gitflow-R/src/Check_On_Merge_Release.sh "$current_wd"
