name: Merging to Dev
run-name: ${{ github.actor }} is merging "${{ github.ref_name }}" to Dev

on:
  workflow_call:
    inputs:
      
      image_to_use:
        required: true
        type: string
      
jobs:
  Unit_tests:
    runs-on: ubuntu-latest
    container: 
      image: ${{ inputs.image_to_use }}
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
         
    steps:
      - name: Show Computing Environment
        id: Show_Computing_Environment
        run: |
          bash
          echo "Checking in ${{ inputs.image_to_use }}"
          . /root/miniconda3/etc/profile.d/conda.sh && conda init bash
          conda activate scworkflow
          conda list

      - run: echo "Checking in ${{ inputs.image_to_use }}"
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Lint All Python Scripts
        id: lint_all
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"

          python -m pip install flake8

          echo "flake8 version:"
          flake8 --version

          echo "Setup git:"
          git config --global --add safe.directory $current_wd
          
          git clone https://github.com/fnlcr-bids-sdsi/gitflow-R.git

          cd gitflow-R
          git checkout single-cell-analysis

          cd $current_wd

          bash $current_wd/gitflow-R/Lint_All.sh
      
      - id: Run_All_Unit_Tests
        name: Run All Unit Tests
        run: |
          bash
          . /root/miniconda3/etc/profile.d/conda.sh && conda init bash
          conda activate scworkflow

          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          
          bash $current_wd/gitflow-R/All_Unit_Tests.sh "$current_wd"
