name: Push Check on Changed Scripts
run-name: Action on push by ${{ github.actor }} 

on:
  workflow_call:
    inputs:
    
      image_to_use:
        required: true
        type: string
      
jobs:
  Check_on_Changed_Scripts:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image_to_use }}
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
         
    steps:
      - uses: actions/checkout@v3
        with:
           token: ${{secrets.GITHUB_TOKEN}}
           ref: ${{ github.ref_name }}
           fetch-depth: 0

      - name: Setup Workflow
        id: setup_workflow
        run: |
          # fetch-depth: 0 it will fetch all history for all branches and tags.
          echo "Checking in ${{ inputs.image_to_use }}"
          bash
          . /root/miniconda3/etc/profile.d/conda.sh && conda init bash
          conda activate scworkflow
          conda list

          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          
          git config --global --add safe.directory $current_wd

          repo_name=${{ github.repository }}
          access_token=${{ secrets.GITHUB_TOKEN }}

          response=$(curl -s -H "Authorization: Bearer $access_token" \
            "https://api.github.com/repos/$repo_name/branches/main")
          
          commit_hash=$(echo "$response" | grep -oP '(?<="sha": ")[^"]+' | head -n 1)

          echo "Latest commit hash of main branch: $commit_hash"
          echo "main_commit_hash=$commit_hash" >> $GITHUB_ENV

          branchName=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/branches/$branchName").

          commit_sha=$(echo "$response" | grep -oP '(?<="sha": ")[^"]+' | head -n 1)

          echo "Current Commit SHA: $commit_sha"

          parent_commit_sha=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/$commit_sha" | grep -oP '(?<="parents": \[{"sha": ")[^"]+' | head -n 1)

          echo "Parent Commit SHA: $parent_commit_sha"

          git log $parent_commit_sha
          

          if [ -z "$parent_commit_sha" ]; then
            echo "Branch $branchName is created from push."
            
            echo "create_on_push=Yes" >> $GITHUB_ENV

            git config --global --add safe.directory /__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}
            default_branch=$(curl -s -H "Authorization: ***" \
              "https://api.github.com/repos/FNLCR-DMAP/SCSAWorkflow" | grep -oP '(?<="default_branch": ")[^"]+' | head -n 1)

          else
            echo "Branch $branchName is not created from push."
            echo "create_on_push=No" >> $GITHUB_ENV
          fi
       
      - id: Lint_check
        name: Use flake8 to check code
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"

          python -m pip install flake8

          echo "flake8 version:"
          flake8 --version

          echo "Setup git:"
          git config --global --add safe.directory $current_wd
          
          git clone https://github.com/fnlcr-bids-sdsi/gitflow-R.git
          
          cd gitflow-R
          git checkout single-cell-analysis

          cd $current_wd

          if [ "${{ env.create_on_push }}" = "Yes" ]; then

            bash $current_wd/gitflow-R/Lint_on_Commit.sh "$current_wd" "${{ env.main_commit_hash }}"

          else

            bash $current_wd/gitflow-R/Lint_on_Commit.sh "$current_wd" "${{ github.event.before }}"

          fi        
          
           
      - id: Unit_Test
        name: Unit test for changed scripts
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"

          bash
          . /root/miniconda3/etc/profile.d/conda.sh && conda init bash
          conda activate scworkflow
          
          pytest --version

          if [ "${{ env.create_on_push }}" = "Yes" ]; then

            bash $current_wd/gitflow-R/Check_on_Commit.sh "$current_wd" "${{ env.main_commit_hash }}"

          else

            bash $current_wd/gitflow-R/Check_on_Commit.sh "$current_wd" "${{ github.event.before }}"

          fi   
    
          
      - name: Undo Push If Not Newly Created
        if: ${{ failure() }}
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"

          if [ "${{ env.create_on_push }}" = "Yes" ]; then

            echo "Branch created from push, no previous versions."

          else

            export MY_GIT_TOKEN=${{secrets.GITHUB_TOKEN}}
            export MY_GIT_USERNAME=${{ github.actor }}
            export MY_GIT_EMAIL=${{ github.event.pusher.email }}
            
            git config --global user.name "$MY_GIT_USERNAME"
            git config --global user.email "$MY_GIT_EMAIL"
            git config --global url."https://api:$MY_GIT_TOKEN@github.com/".insteadOf "https://github.com/"
            git config --global url."https://ssh:$MY_GIT_TOKEN@github.com/".insteadOf "ssh://git@github.com/"
            git config --global url."https://git:$MY_GIT_TOKEN@github.com/".insteadOf "git@github.com:"
            
            git clone https://github.com/${GITHUB_REPOSITORY}.git
            
            cd ${GITHUB_REPOSITORY#*/}
            
            git checkout ${{ github.ref_name }}
            
            git reset --hard ${{ github.event.before }}

          fi  
          

          
          