name: Merging to Release
run-name: ${{ github.actor }} is merging "${{ github.ref_name }}" to Release

on:
  workflow_call:
    inputs:
      
      image_to_use:
        required: true
        type: string
      
jobs:
  Unit_tests:
    runs-on: ubuntu-latest
    container: 
      image: ${{ inputs.image_to_use }}
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
         
    steps:
      - name: Show Computing Environment
        id: Show_Computing_Environment
        run: |
          bash
          echo "Checking in ${{ inputs.image_to_use }}"
          . /root/miniconda3/etc/profile.d/conda.sh && conda init bash
          conda activate scworkflow
          conda list

      - run: echo "Checking in ${{ inputs.image_to_use }}"
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Lint All Python Scripts
        id: lint_all
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"

          python -m pip install flake8

          echo "flake8 version:"
          flake8 --version

          echo "Setup git:"
          git config --global --add safe.directory $current_wd
          
          git clone https://github.com/fnlcr-bids-sdsi/gitflow-R.git

          cd gitflow-R
          git checkout single-cell-analysis

          cd $current_wd

          bash $current_wd/gitflow-R/Lint_All.sh
      
      - id: Run_All_Unit_Tests
        name: Run All Unit Tests
        run: |
          bash
          . /root/miniconda3/etc/profile.d/conda.sh && conda init bash
          conda activate scworkflow

          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          
          bash $current_wd/gitflow-R/All_Unit_Tests.sh "$current_wd"

            - name: Generating Documentations

      - name: Version Update 
        if: ${{ success() }}
        run: |
          bash
          . /root/miniconda3/etc/profile.d/conda.sh && conda init bash
          conda activate scworkflow

          pip --version

          pip install python-semantic-release

          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          cd $current_wd
          
          export MY_GIT_TOKEN=${{ secrets.GITHUB_TOKEN }}
          export MY_GIT_USERNAME=${{ github.actor }}
          export MY_GIT_EMAIL=${{ github.event.pusher.email }}
          
          git config --global user.name "$MY_GIT_USERNAME"
          git config --global user.email "$MY_GIT_EMAIL"
          git config --global url."https://api:$MY_GIT_TOKEN@github.com/".insteadOf "https://github.com/"
          git config --global url."https://ssh:$MY_GIT_TOKEN@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://git:$MY_GIT_TOKEN@github.com/".insteadOf "git@github.com:"
          
          git config --global --add safe.directory "$current_wd"

          cd $current_wd
          
          git clone https://github.com/${GITHUB_REPOSITORY}.git
          
          cd ${GITHUB_REPOSITORY#*/}

          git checkout ${{ github.base_ref }}

          semantic-release version

          git commit -a -m "docs(version): Update version numebr."

          git push -f origin ${{ github.base_ref }}

          echo "Process completed."

          