name: Merging to main
run-name: ${{ github.actor }} is merging "${{ github.ref_name }}" to main

on:
  workflow_call:
    inputs:
      
      image_to_use:
      required: true
      type: string

jobs:
  Integration_Test_and_Check:
    runs-on: ubuntu-latest
    container: 
      image: ${{ inputs.image_to_use }}
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
         
    steps:
      - run: echo "Running test in ${{ inputs.image_to_use }}"
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      
      - id: Build_check
        name: R Build and Checks
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          
          git clone https://github.com/fnlcr-bids-sdsi/gitflow-R.git
          
          bash $current_wd/gitflow-R/Check_On_Merge_Main.sh "$current_wd"
