name: Merging to main
run-name: ${{ github.actor }} is merging "${{ github.head_ref }}" to main

on:
  workflow_call:
    inputs:
    
      image_to_use:
        required: true
        type: string

jobs:
  Integration_Test_and_Check:
    runs-on: ubuntu-latest
    container: 
      image: ${{ inputs.image_to_use }}
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
         
    steps:
      - name: Show Computing Environment
        id: Show_Computing_Environment
        run: |
          echo "Checking in ${{ inputs.image_to_use }}"
          bash
          . /root/miniconda3/etc/profile.d/conda.sh && conda init bash
          conda activate scworkflow
          conda list

      - run: echo "Running test in ${{ inputs.image_to_use }}"
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Lint All Python Scripts
        id: lint_all
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"

          python -m pip install flake8

          echo "flake8 version:"
          flake8 --version

          echo "Setup git:"
          git config --global --add safe.directory $current_wd
          
          git clone https://github.com/fnlcr-bids-sdsi/gitflow-R.git

          cd gitflow-R
          git checkout single-cell-analysis

          cd $current_wd

          bash $current_wd/gitflow-R/Lint_All.sh
 
      
      - id: Build_check
        name: Run All Tests
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          bash
          . /root/miniconda3/etc/profile.d/conda.sh && conda init bash
          conda activate scworkflow
          
          bash $current_wd/gitflow-R/Check_On_Merge_Main.sh "$current_wd"

      - name: Checking Version 
        run: |
          bash
          . /root/miniconda3/etc/profile.d/conda.sh && conda init bash
          conda activate scworkflow

          pip --version

          pip install python-semantic-release

          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          cd $current_wd
          
          export MY_GIT_TOKEN=${{ secrets.GITHUB_TOKEN }}
          export MY_GIT_USERNAME=${{ github.actor }}
          export MY_GIT_EMAIL=${{ github.event.pusher.email }}
          
          git config --global user.name "$MY_GIT_USERNAME"
          git config --global user.email "$MY_GIT_EMAIL"
          git config --global url."https://api:$MY_GIT_TOKEN@github.com/".insteadOf "https://github.com/"
          git config --global url."https://ssh:$MY_GIT_TOKEN@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://git:$MY_GIT_TOKEN@github.com/".insteadOf "git@github.com:"
          
          git config --global --add safe.directory "$current_wd"

          cd $current_wd
          
          git clone https://github.com/${GITHUB_REPOSITORY}.git
          
          cd ${GITHUB_REPOSITORY#*/}

          git checkout ${{ github.head_ref }}
          
          line="[tool.semantic_release]"
          version_variable="version_variable = \"pyproject.toml:version\""

          if grep -Fxq "$line" pyproject.toml && \
            grep -Fxq "$version_variable" pyproject.toml; then

              echo "Semantic release setting already exists in pyproject.toml"

          else
              echo "" >> pyproject.toml
              echo "$line" >> pyproject.toml
              echo "$version_variable" >> pyproject.toml
              echo "Added semantic release setting to pyproject.toml"
              echo "" >> pyproject.toml
          fi


          commit="6489dca50d43731cbf10739efa08ca9086cbd0fa"
          tag="v0.1.0"

          if git tag --list "$tag" --contains "$commit" >/dev/null 2>&1; then
              echo "Tag $tag already exists for commit $commit. Skipping tagging."
          else
              git tag "$tag" "$commit"
              echo "Tag $tag created for commit $commit."
          fi
          
          version_log=$(semantic-release version)

          echo "version_log=$version_log" >> $GITHUB_ENV
      
      - name: Display Version Log
        run: |
          echo "${{ env.version_log }}"
