name: Merging to main
run-name: ${{ github.actor }} is merging "${{ github.ref_name }}" to main

on:
  workflow_call:
    inputs:
    
      image_to_use:
        required: true
        type: string

jobs:
  Integration_Test_and_Check:
    runs-on: ubuntu-latest
    container: 
      image: ${{ inputs.image_to_use }}
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
         
    steps:
      - name: Show Computing Environment
        id: Show_Computing_Environment
        run: |
          echo "Checking in ${{ inputs.image_to_use }}"
          bash
          . /root/miniconda3/etc/profile.d/conda.sh && conda init bash
          conda activate scworkflow
          conda list

      - run: echo "Running test in ${{ inputs.image_to_use }}"
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Lint All Python Scripts
        id: lint_all
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"

          python -m pip install flake8

          echo "flake8 version:"
          flake8 --version

          echo "Setup git:"
          git config --global --add safe.directory $current_wd
          
          git clone https://github.com/fnlcr-bids-sdsi/gitflow-R.git

          cd gitflow-R
          git checkout single-cell-analysis

          cd $current_wd

          bash $current_wd/gitflow-R/Lint_All.sh
 
      
      - id: Build_check
        name: Run All Tests
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          bash
          . /root/miniconda3/etc/profile.d/conda.sh && conda init bash
          conda activate scworkflow
          
          bash $current_wd/gitflow-R/Check_On_Merge_Main.sh "$current_wd"
