name: Gitflow-R Parser for DSPWorkflow
run-name: Activated by ${{ github.actor }} 

on:
  workflow_call:
    inputs:
    
      image_to_use:
        required: true
        type: string
      
      verions_to_use:
        required: false
        default: main
        type: string
        
      test:
        required: false
        default: No
        type: string

      artifact_rid_production:
        required: false
        type: string
        default: "ri.artifacts.main.repository.20ce29a2-3803-4eae-b325-8fe367d47d1e"
      
      artifact_rid_development:
        required: false
        type: string
        default: "ri.artifacts.main.repository.be0ad467-35f6-438d-befc-760a8f723b17"

      package_name:
        required: false
        type: string
        default: 'r-dspworkflow'

      r_version:
        required: false
        type: string
        default: '4.1.3'
  
    secrets:
      NIDAP_TOKEN_PRODUCTION:
        required: false
      NIDAP_TOKEN_DEVELOPMENT:
        required: false
        
jobs:
  Activate_Action_Pack:
    if: ${{ inputs.verions_to_use == 'main' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Action_pack_verion_main.yml@master
    with:
      image_to_use: "${{ inputs.image_to_use }}"
      test: "${{ inputs.test }}"
      artifact_rid_production: "${{ inputs.artifact_rid_production }}"
      artifact_rid_development: "${{ inputs.artifact_rid_development }}"
      package_name: "${{ inputs.package_name }}"
      r_version: "${{ inputs.r_version }}"

    secrets:
      NIDAP_TOKEN_PRODUCTION: "${{ secrets.NIDAP_TOKEN_PRODUCTION }}"
      NIDAP_TOKEN_DEVELOPMENT: "${{ secrets.NIDAP_TOKEN_DEVELOPMENT }}"
       
