name: Gitflow-R Parser for DSPWorkflow
run-name: Activated by ${{ github.actor }} 

on:
  workflow_call:
    inputs:
    
      image_to_use:
        required: true
        type: string
      
      verions_to_use:
        required: false
        default: main
        type: string
        
      test:
        required: false
        default: No
        type: string
      
      action_branch:
        required: false
        default: 'master'
        type: string
  
  secrets:
    PAT:
      required: false
        
jobs:
  Activate_Action_Pack:
    if: ${{ inputs.verions_to_use == 'main' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Action_pack_verion_main.yml@DSPWorkflow
    with:
      image_to_use: "${{ inputs.image_to_use }}"
      test: "${{ inputs.test }}"
      action_branch: "${{ inputs.action_branch }}"
    secrets:
      PAT: ${{ secrets.PAT }}
       
