name: Gitflow-R Parser
run-name: Activated by ${{ github.actor }} 

on:
  workflow_call:
    inputs:
    
      image_to_use:
        required: true
        type: string
      
      verions_to_use:
        required: false
        default: main
        type: string
        
      test:
        required: false
        default: No
        type: string
        
jobs:
  Activate_Action_Pack:
    if: ${{ inputs.verions_to_use == 'main' }}
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Action_pack_verion_main.yml@master
    with:
      event_name: "${{ github.event_name }}"
      pull_merged: "${{ github.event.pull_request.merged }}"
      event_branch: "${{ github.ref_name#refs/heads/ }}" 
      image_to_use: "${{ inputs.image_to_use }}"

       